server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codenews
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: rafinhalvarenga@gmail.com
    password: nabj imtg sury vfcl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      news: codenews-news

    consumer:
      group-id: codenews-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          trusted:
            packages: org.codenews.model
          value:
            default:
              type: org.codenews.model.News

    # Tamanho de lote para newsletter (batch):
    newsletter:
      batch:
        size: 10

scheduler:
  cron:
    daily: 0 47 23 * * *
