server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codenews
    username: postgres
    password: abc123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: rafinhalvarenga@gmail.com
    password: nabj imtg sury vfcl
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
      mail.smtp.debug: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: codenews-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    newsletter:
      batch:
        size: 1